// AUTO-GENERATED by tools/buildHighlight.ts from source/lilylet/lilylet.jison.
// Do NOT edit by hand. Run `npm run build:highlight` to regenerate.
//
// Framework-agnostic syntax-highlighting definition for Lilylet, derived from
// the grammar's lexer so it never drifts from the language. No editor
// dependency: it exposes generic SCOPE names and a longest-match tokenizer.
// Downstream editors (CodeMirror, Monaco, Prism, ...) map SCOPE -> their theme.

/** Generic highlight scopes Lilylet tokens can carry. */
export type HighlightScope =
	| "articulation"
	| "bar"
	| "brace"
	| "chordBracket"
	| "comment"
	| "dynamic"
	| "grace"
	| "hairpin"
	| "header"
	| "keyword"
	| "markup"
	| "mode"
	| "navigation"
	| "number"
	| "octave"
	| "operator"
	| "ornament"
	| "paren"
	| "pedal"
	| "pitch"
	| "punctuation"
	| "rest"
	| "separator"
	| "squareBracket"
	| "stem"
	| "string"
	| "tie"
	| "tuplet";

export interface HighlightRule {
	/** Sticky, case-insensitive regex anchored at the scan position. */
	re: RegExp;
	scope: HighlightScope;
}

export interface HighlightToken {
	scope: HighlightScope;
	/** Start offset within the line (inclusive). */
	start: number;
	/** End offset within the line (exclusive). */
	end: number;
}

/**
 * Ordered highlight rules. Order mirrors the grammar's lexer; the tokenizer
 * applies LONGEST-match (flex semantics), using order only as a tie-breaker.
 */
export const HIGHLIGHT_RULES: HighlightRule[] = [
	{ re: /\%.*/iy, scope: "comment" },
	{ re: /\[title/iy, scope: "header" },
	{ re: /\[subtitle/iy, scope: "header" },
	{ re: /\[composer/iy, scope: "header" },
	{ re: /\[arranger/iy, scope: "header" },
	{ re: /\[lyricist/iy, scope: "header" },
	{ re: /\[opus/iy, scope: "header" },
	{ re: /\[instrument\-[A-Za-z0-9_]+(?:\-[A-Za-z0-9_]+)*/iy, scope: "header" },
	{ re: /\[instrument/iy, scope: "header" },
	{ re: /\[genre/iy, scope: "header" },
	{ re: /\[staves/iy, scope: "header" },
	{ re: /\[auto\-beam/iy, scope: "header" },
	{ re: /\]/iy, scope: "squareBracket" },
	{ re: /"[^"]*"/iy, scope: "string" },
	{ re: /\\clef/iy, scope: "keyword" },
	{ re: /\\key/iy, scope: "keyword" },
	{ re: /\\time/iy, scope: "keyword" },
	{ re: /\\partial/iy, scope: "keyword" },
	{ re: /\\numericTimeSignature/iy, scope: "keyword" },
	{ re: /\\defaultTimeSignature/iy, scope: "keyword" },
	{ re: /\\tempo/iy, scope: "keyword" },
	{ re: /\\staff/iy, scope: "keyword" },
	{ re: /\\grace/iy, scope: "grace" },
	{ re: /\\times/iy, scope: "tuplet" },
	{ re: /\\tuplet/iy, scope: "tuplet" },
	{ re: /\\repeat/iy, scope: "keyword" },
	{ re: /\\ottava/iy, scope: "keyword" },
	{ re: /\\stemUp/iy, scope: "stem" },
	{ re: /\\stemDown/iy, scope: "stem" },
	{ re: /\\stemNeutral/iy, scope: "stem" },
	{ re: /\\major/iy, scope: "mode" },
	{ re: /\\minor/iy, scope: "mode" },
	{ re: /\\sustainOn/iy, scope: "pedal" },
	{ re: /\\sustainOff/iy, scope: "pedal" },
	{ re: /\\bar/iy, scope: "keyword" },
	{ re: /\\coda/iy, scope: "navigation" },
	{ re: /\\segno/iy, scope: "navigation" },
	{ re: /\\chords/iy, scope: "keyword" },
	{ re: /\\markup/iy, scope: "markup" },
	{ re: /\\</iy, scope: "hairpin" },
	{ re: /\\>/iy, scope: "hairpin" },
	{ re: /\\!/iy, scope: "hairpin" },
	{ re: /\\staccato/iy, scope: "articulation" },
	{ re: /\\staccatissimo/iy, scope: "articulation" },
	{ re: /\\tenuto/iy, scope: "articulation" },
	{ re: /\\marcato/iy, scope: "articulation" },
	{ re: /\\accent/iy, scope: "articulation" },
	{ re: /\\portato/iy, scope: "articulation" },
	{ re: /\\trill/iy, scope: "ornament" },
	{ re: /\\turn/iy, scope: "ornament" },
	{ re: /\\mordent/iy, scope: "ornament" },
	{ re: /\\prall/iy, scope: "ornament" },
	{ re: /\\fermata/iy, scope: "ornament" },
	{ re: /\\shortfermata/iy, scope: "ornament" },
	{ re: /\\arpeggio/iy, scope: "ornament" },
	{ re: /\\ppp/iy, scope: "dynamic" },
	{ re: /\\pp/iy, scope: "dynamic" },
	{ re: /\\mp/iy, scope: "dynamic" },
	{ re: /\\mf/iy, scope: "dynamic" },
	{ re: /\\fff/iy, scope: "dynamic" },
	{ re: /\\ff/iy, scope: "dynamic" },
	{ re: /\\sfz/iy, scope: "dynamic" },
	{ re: /\\rfz/iy, scope: "dynamic" },
	{ re: /\\sf/iy, scope: "dynamic" },
	{ re: /\\fp/iy, scope: "dynamic" },
	{ re: /\\p/iy, scope: "dynamic" },
	{ re: /\\f/iy, scope: "dynamic" },
	{ re: /\\rest/iy, scope: "rest" },
	{ re: /\\\\\\/iy, scope: "separator" },
	{ re: /\\\\/iy, scope: "separator" },
	{ re: /tremolo/iy, scope: "keyword" },
	{ re: /[a-g](ss|ff|s|f)?/iy, scope: "pitch" },
	{ re: /'/iy, scope: "octave" },
	{ re: /,/iy, scope: "octave" },
	{ re: /[0-9]+/iy, scope: "number" },
	{ re: /\//iy, scope: "operator" },
	{ re: /#/iy, scope: "punctuation" },
	{ re: /\{/iy, scope: "brace" },
	{ re: /\}/iy, scope: "brace" },
	{ re: /</iy, scope: "chordBracket" },
	{ re: />/iy, scope: "chordBracket" },
	{ re: /\|/iy, scope: "bar" },
	{ re: /\[/iy, scope: "squareBracket" },
	{ re: /\]/iy, scope: "squareBracket" },
	{ re: /\(/iy, scope: "paren" },
	{ re: /\)/iy, scope: "paren" },
	{ re: /~/iy, scope: "tie" },
	{ re: /\./iy, scope: "punctuation" },
	{ re: /-/iy, scope: "punctuation" },
	{ re: /[_]/iy, scope: "punctuation" },
	{ re: /\^/iy, scope: "punctuation" },
	{ re: /!/iy, scope: "punctuation" },
	{ re: /:/iy, scope: "operator" },
	{ re: /=/iy, scope: "operator" },
	{ re: /[rR]/iy, scope: "rest" },
	{ re: /[sS]/iy, scope: "rest" },
];

/**
 * Match a single token at `pos` in `line` using longest-match. Returns the
 * winning token, or null if no rule matches (caller should advance one char).
 */
export const matchAt = (line: string, pos: number): HighlightToken | null => {
	let best: HighlightToken | null = null;
	for (const rule of HIGHLIGHT_RULES) {
		rule.re.lastIndex = pos;
		const m = rule.re.exec(line);
		if (m && m.index === pos && m[0].length > 0) {
			const end = pos + m[0].length;
			if (!best || end > best.end)
				best = { scope: rule.scope, start: pos, end };
		}
	}
	return best;
};

/**
 * Tokenize one line into a list of scoped spans. Characters that match no rule
 * are skipped (no token emitted), mirroring the lexer's catch-all.
 */
export const tokenizeLine = (line: string): HighlightToken[] => {
	const tokens: HighlightToken[] = [];
	let pos = 0;
	while (pos < line.length) {
		const tok = matchAt(line, pos);
		if (tok) {
			tokens.push(tok);
			pos = tok.end;
		} else {
			pos++;
		}
	}
	return tokens;
};
