// AUTO-GENERATED by tools/buildHighlight.ts from source/lilylet/grammar.jison.js.
// Do NOT edit by hand. Run `npm run build:highlight` to regenerate.
//
// Framework-agnostic syntax-highlighting definition for Lilylet, derived from
// the grammar's lexer so it never drifts from the language. No editor
// dependency: it exposes generic SCOPE names and a longest-match tokenizer.
// Downstream editors (CodeMirror, Monaco, Prism, ...) map SCOPE -> their theme.

/** Generic highlight scopes Lilylet tokens can carry. */
export type HighlightScope =
	| "articulation"
	| "bar"
	| "brace"
	| "chordBracket"
	| "comment"
	| "dynamic"
	| "grace"
	| "hairpin"
	| "header"
	| "keyword"
	| "markup"
	| "mode"
	| "navigation"
	| "number"
	| "octave"
	| "operator"
	| "ornament"
	| "paren"
	| "pedal"
	| "pitch"
	| "punctuation"
	| "rest"
	| "separator"
	| "squareBracket"
	| "stem"
	| "string"
	| "tie"
	| "tuplet";

export interface HighlightRule {
	/** Sticky, case-insensitive regex anchored at the scan position. */
	re: RegExp;
	scope: HighlightScope;
}

export interface HighlightToken {
	scope: HighlightScope;
	/** Start offset within the line (inclusive). */
	start: number;
	/** End offset within the line (exclusive). */
	end: number;
}

/**
 * Ordered highlight rules. Order mirrors the grammar's lexer; the tokenizer
 * applies LONGEST-match (flex semantics), using order only as a tie-breaker.
 */
export const HIGHLIGHT_RULES: HighlightRule[] = [
	{ re: /(?:%.*)/iy, scope: "comment" },
	{ re: /(?:\[title\b)/iy, scope: "header" },
	{ re: /(?:\[subtitle\b)/iy, scope: "header" },
	{ re: /(?:\[composer\b)/iy, scope: "header" },
	{ re: /(?:\[arranger\b)/iy, scope: "header" },
	{ re: /(?:\[lyricist\b)/iy, scope: "header" },
	{ re: /(?:\[opus\b)/iy, scope: "header" },
	{ re: /(?:\[instrument-[A-Za-z0-9_]+(?:-[A-Za-z0-9_]+)*)/iy, scope: "header" },
	{ re: /(?:\[instrument\b)/iy, scope: "header" },
	{ re: /(?:\[genre\b)/iy, scope: "header" },
	{ re: /(?:\[staves\b)/iy, scope: "header" },
	{ re: /(?:\[auto-beam\b)/iy, scope: "header" },
	{ re: /(?:\])/iy, scope: "squareBracket" },
	{ re: /(?:"[^"]*")/iy, scope: "string" },
	{ re: /(?:\\clef\b)/iy, scope: "keyword" },
	{ re: /(?:\\key\b)/iy, scope: "keyword" },
	{ re: /(?:\\time\b)/iy, scope: "keyword" },
	{ re: /(?:\\partial\b)/iy, scope: "keyword" },
	{ re: /(?:\\numericTimeSignature\b)/iy, scope: "keyword" },
	{ re: /(?:\\defaultTimeSignature\b)/iy, scope: "keyword" },
	{ re: /(?:\\tempo\b)/iy, scope: "keyword" },
	{ re: /(?:\\staff\b)/iy, scope: "keyword" },
	{ re: /(?:\\grace\b)/iy, scope: "grace" },
	{ re: /(?:\\times\b)/iy, scope: "tuplet" },
	{ re: /(?:\\tuplet\b)/iy, scope: "tuplet" },
	{ re: /(?:\\repeat\b)/iy, scope: "keyword" },
	{ re: /(?:\\ottava\b)/iy, scope: "keyword" },
	{ re: /(?:\\stemUp\b)/iy, scope: "stem" },
	{ re: /(?:\\stemDown\b)/iy, scope: "stem" },
	{ re: /(?:\\stemNeutral\b)/iy, scope: "stem" },
	{ re: /(?:\\major\b)/iy, scope: "mode" },
	{ re: /(?:\\minor\b)/iy, scope: "mode" },
	{ re: /(?:\\sustainOn\b)/iy, scope: "pedal" },
	{ re: /(?:\\sustainOff\b)/iy, scope: "pedal" },
	{ re: /(?:\\bar\b)/iy, scope: "keyword" },
	{ re: /(?:\\coda\b)/iy, scope: "navigation" },
	{ re: /(?:\\segno\b)/iy, scope: "navigation" },
	{ re: /(?:\\chords\b)/iy, scope: "keyword" },
	{ re: /(?:\\markup\b)/iy, scope: "markup" },
	{ re: /(?:\\<)/iy, scope: "hairpin" },
	{ re: /(?:\\>)/iy, scope: "hairpin" },
	{ re: /(?:\\!)/iy, scope: "hairpin" },
	{ re: /(?:\\staccato\b)/iy, scope: "articulation" },
	{ re: /(?:\\staccatissimo\b)/iy, scope: "articulation" },
	{ re: /(?:\\tenuto\b)/iy, scope: "articulation" },
	{ re: /(?:\\marcato\b)/iy, scope: "articulation" },
	{ re: /(?:\\accent\b)/iy, scope: "articulation" },
	{ re: /(?:\\portato\b)/iy, scope: "articulation" },
	{ re: /(?:\\trill\b)/iy, scope: "ornament" },
	{ re: /(?:\\turn\b)/iy, scope: "ornament" },
	{ re: /(?:\\mordent\b)/iy, scope: "ornament" },
	{ re: /(?:\\prall\b)/iy, scope: "ornament" },
	{ re: /(?:\\fermata\b)/iy, scope: "ornament" },
	{ re: /(?:\\shortfermata\b)/iy, scope: "ornament" },
	{ re: /(?:\\arpeggio\b)/iy, scope: "ornament" },
	{ re: /(?:\\ppp\b)/iy, scope: "dynamic" },
	{ re: /(?:\\pp\b)/iy, scope: "dynamic" },
	{ re: /(?:\\mp\b)/iy, scope: "dynamic" },
	{ re: /(?:\\mf\b)/iy, scope: "dynamic" },
	{ re: /(?:\\fff\b)/iy, scope: "dynamic" },
	{ re: /(?:\\ff\b)/iy, scope: "dynamic" },
	{ re: /(?:\\sfz\b)/iy, scope: "dynamic" },
	{ re: /(?:\\rfz\b)/iy, scope: "dynamic" },
	{ re: /(?:\\sf\b)/iy, scope: "dynamic" },
	{ re: /(?:\\fp\b)/iy, scope: "dynamic" },
	{ re: /(?:\\p\b)/iy, scope: "dynamic" },
	{ re: /(?:\\f)/iy, scope: "dynamic" },
	{ re: /(?:\\rest\b)/iy, scope: "rest" },
	{ re: /(?:\\\\\\)/iy, scope: "separator" },
	{ re: /(?:\\\\)/iy, scope: "separator" },
	{ re: /(?:tremolo\b)/iy, scope: "keyword" },
	{ re: /(?:[a-g](ss|ff|s|f)?)/iy, scope: "pitch" },
	{ re: /(?:')/iy, scope: "octave" },
	{ re: /(?:,)/iy, scope: "octave" },
	{ re: /(?:[0-9]+)/iy, scope: "number" },
	{ re: /(?:\/)/iy, scope: "operator" },
	{ re: /(?:#)/iy, scope: "punctuation" },
	{ re: /(?:\{)/iy, scope: "brace" },
	{ re: /(?:\})/iy, scope: "brace" },
	{ re: /(?:<)/iy, scope: "chordBracket" },
	{ re: /(?:>)/iy, scope: "chordBracket" },
	{ re: /(?:\|)/iy, scope: "bar" },
	{ re: /(?:\[)/iy, scope: "squareBracket" },
	{ re: /(?:\])/iy, scope: "squareBracket" },
	{ re: /(?:\()/iy, scope: "paren" },
	{ re: /(?:\))/iy, scope: "paren" },
	{ re: /(?:~)/iy, scope: "tie" },
	{ re: /(?:\.)/iy, scope: "punctuation" },
	{ re: /(?:-)/iy, scope: "punctuation" },
	{ re: /(?:[_])/iy, scope: "punctuation" },
	{ re: /(?:\^)/iy, scope: "punctuation" },
	{ re: /(?:!)/iy, scope: "punctuation" },
	{ re: /(?::)/iy, scope: "operator" },
	{ re: /(?:=)/iy, scope: "operator" },
	{ re: /(?:[rR])/iy, scope: "rest" },
	{ re: /(?:[sS])/iy, scope: "rest" },
];

/**
 * Match a single token at `pos` in `line` using longest-match. Returns the
 * winning token, or null if no rule matches (caller should advance one char).
 */
export const matchAt = (line: string, pos: number): HighlightToken | null => {
	let best: HighlightToken | null = null;
	for (const rule of HIGHLIGHT_RULES) {
		rule.re.lastIndex = pos;
		const m = rule.re.exec(line);
		if (m && m.index === pos && m[0].length > 0) {
			const end = pos + m[0].length;
			if (!best || end > best.end)
				best = { scope: rule.scope, start: pos, end };
		}
	}
	return best;
};

/**
 * Tokenize one line into a list of scoped spans. Characters that match no rule
 * are skipped (no token emitted), mirroring the lexer's catch-all.
 */
export const tokenizeLine = (line: string): HighlightToken[] => {
	const tokens: HighlightToken[] = [];
	let pos = 0;
	while (pos < line.length) {
		const tok = matchAt(line, pos);
		if (tok) {
			tokens.push(tok);
			pos = tok.end;
		} else {
			pos++;
		}
	}
	return tokens;
};
