import * as fs from "fs";
import * as path from "path";
import * as crypto from "crypto";
import * as lilylet from "../source/lilylet/index.js";

const UNIT_CASES_DIR = path.join(import.meta.dirname, "assets/unit-cases");
const OUTPUT_FILE = path.join(import.meta.dirname, "assets/mei-hashes.yaml");

const updateMode = process.argv.includes("--update");

// Parse existing yaml as a flat key:value map (no nesting, comments-aware).
const loadExisting = (file: string): Map<string, string> => {
	const map = new Map<string, string>();
	if (!fs.existsSync(file)) return map;
	const text = fs.readFileSync(file, "utf-8");
	for (const raw of text.split("\n")) {
		const line = raw.trim();
		if (!line || line.startsWith("#")) continue;
		const m = line.match(/^([^:]+):\s*(.+)$/);
		if (m) map.set(m[1].trim(), m[2].trim());
	}
	return map;
};

const previous = loadExisting(OUTPUT_FILE);
const files = fs.readdirSync(UNIT_CASES_DIR).filter(f => f.endsWith(".lyl")).sort();

const lines: string[] = [
	"# MD5 hashes of MEI output for each .lyl unit case.",
	"# Generated by tests/computeMeiHashes.ts — regenerate with `--update` after intentional encoder changes.",
	"",
];

const mismatches: { file: string; expected: string; actual: string }[] = [];
const added: string[] = [];

for (const file of files) {
	const lyl = fs.readFileSync(path.join(UNIT_CASES_DIR, file), "utf-8");
	const doc = lilylet.parseCode(lyl);
	const mei = lilylet.meiEncoder.encode(doc);
	// Strip xml:id attributes and ID references (#note-..., #chord-...) — these
	// embed Math.random()-derived sessionPrefix and change between runs.
	const normalized = mei
		.replace(/\s+xml:id="[^"]*"/g, "")
		.replace(/="#[^"]*"/g, '="#"');
	const hash = crypto.createHash("md5").update(normalized).digest("hex");
	lines.push(`${file}: ${hash}`);

	const prev = previous.get(file);
	if (prev === undefined) {
		added.push(file);
	} else if (prev !== hash) {
		mismatches.push({ file, expected: prev, actual: hash });
	}
}

const removed: string[] = [];
for (const key of previous.keys()) {
	if (!files.includes(key)) removed.push(key);
}

if (updateMode) {
	fs.writeFileSync(OUTPUT_FILE, lines.join("\n") + "\n");
	console.log(`Wrote ${files.length} hashes to ${OUTPUT_FILE}`);
	if (mismatches.length) console.log(`(${mismatches.length} hash(es) changed, ${added.length} added, ${removed.length} removed)`);
	process.exit(0);
}

if (mismatches.length === 0 && added.length === 0 && removed.length === 0) {
	console.log(`OK: ${files.length} MEI hashes match the recorded values.`);
	process.exit(0);
}

if (mismatches.length > 0) {
	console.error(`MEI hash mismatch in ${mismatches.length} file(s):`);
	for (const m of mismatches) {
		console.error(`  - ${m.file}`);
		console.error(`      expected: ${m.expected}`);
		console.error(`      actual:   ${m.actual}`);
	}
}
if (added.length > 0) {
	console.error(`New file(s) without recorded hash (${added.length}):`);
	for (const f of added) console.error(`  - ${f}`);
}
if (removed.length > 0) {
	console.error(`Recorded hash for missing file(s) (${removed.length}):`);
	for (const f of removed) console.error(`  - ${f}`);
}
console.error(`\nIf the change is intentional, run: npx tsx tests/computeMeiHashes.ts --update`);
process.exit(1);
